# Generated by Django 4.0.4 on 2022-06-11 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DorZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('acc', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Директоры',
                'verbose_name_plural': 'Директоры',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gradeName', models.CharField(max_length=100, unique=True, verbose_name='Класс')),
            ],
            options={
                'verbose_name': 'Классы',
                'verbose_name_plural': 'Классы',
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('acc', models.IntegerField(blank=True, null=True, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Родители',
                'verbose_name_plural': 'Родители',
            },
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('acc', models.IntegerField(blank=True, null=True, verbose_name='Баланс')),
                ('grade_p', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.grade', verbose_name='Класс')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ученики',
                'verbose_name_plural': 'Ученики',
            },
        ),
        migrations.CreateModel(
            name='SchoolBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolBalanceUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('acc', models.IntegerField(blank=True, null=True, verbose_name='Баланс')),
                ('grade_t', models.ManyToManyField(to='wisapp.grade', verbose_name='Закрепленные классы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Учителя',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Transfers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('pupil', models.ManyToManyField(to='wisapp.pupil', verbose_name='Выберете ученика')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.teacher')),
                ('transfer_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wisapp.grade')),
            ],
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pupil', models.ManyToManyField(to='wisapp.pupil', verbose_name='Выберете ученика')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.teacher')),
                ('transfer_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wisapp.grade')),
            ],
        ),
        migrations.CreateModel(
            name='SuperUTransTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ManyToManyField(to='wisapp.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.schoolbalanceuser')),
            ],
        ),
        migrations.CreateModel(
            name='SuperUTransT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('teacher', models.ManyToManyField(to='wisapp.teacher')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.schoolbalanceuser')),
            ],
        ),
        migrations.CreateModel(
            name='SuperUTransDH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('dorz', models.ManyToManyField(to='wisapp.dorz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.schoolbalanceuser')),
            ],
        ),
        migrations.CreateModel(
            name='SuperUTransD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('dorz', models.ManyToManyField(to='wisapp.dorz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.schoolbalanceuser')),
            ],
        ),
        migrations.CreateModel(
            name='PointTransParents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('point_sum', models.PositiveIntegerField(default=0)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.parent')),
            ],
        ),
        migrations.CreateModel(
            name='PointTrans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.IntegerField(default=0)),
                ('point_sum', models.PositiveIntegerField(default=0)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='ParentTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.parent')),
                ('pupil', models.ManyToManyField(to='wisapp.pupil', verbose_name='Выберете ученика')),
            ],
        ),
        migrations.CreateModel(
            name='ParentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.parent')),
                ('pupil', models.ManyToManyField(to='wisapp.pupil', verbose_name='Выберете ученика')),
            ],
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ManyToManyField(to='wisapp.pupil', verbose_name='Ученик'),
        ),
        migrations.AddField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FineParentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.parent')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil', verbose_name='Выберете ученика')),
            ],
        ),
        migrations.CreateModel(
            name='FineParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('parent_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.parent')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil', verbose_name='Выберете ученика')),
            ],
        ),
        migrations.CreateModel(
            name='FineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil', verbose_name='Выберете ученика')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.teacher')),
                ('transfer_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wisapp.grade')),
            ],
        ),
        migrations.CreateModel(
            name='FineDorZHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dorz_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.dorz')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='FineDorZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('dorz_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.dorz')),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil', verbose_name='Выберете ученика')),
                ('teacher_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.teacher')),
                ('transfer_grade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wisapp.grade')),
            ],
        ),
        migrations.CreateModel(
            name='DorZTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('dorz_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.dorz')),
                ('pupil', models.ManyToManyField(to='wisapp.pupil')),
            ],
        ),
        migrations.CreateModel(
            name='DorZTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('dorz_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.dorz')),
                ('pupil', models.ManyToManyField(to='wisapp.pupil')),
            ],
        ),
    ]
