# Generated by Django 4.0.4 on 2022-06-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointtrans',
            options={'verbose_name': 'Переводы учителей', 'verbose_name_plural': 'Переводы учителей'},
        ),
        migrations.AlterModelOptions(
            name='pointtransparents',
            options={'verbose_name': 'Переводы родителей', 'verbose_name_plural': 'Переводы родителей'},
        ),
        migrations.AlterField(
            model_name='dorz',
            name='acc',
            field=models.PositiveIntegerField(default=0, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='dorz',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='dorztransferhistory',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='finedorzhistory',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='finehistory',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='fineparenthistory',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='parenttransferhistory',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='pointtrans',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='pointtransparents',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='schoolbalance',
            name='balance',
            field=models.PositiveBigIntegerField(verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='schoolbalanceuser',
            name='lastName',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='schoolbalanceuser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='superutransth',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
    ]
