# Generated by Django 4.0.4 on 2022-06-24 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0002_alter_pointtrans_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBalanceAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.schoolbalanceuser')),
            ],
        ),
    ]
