# Generated by Django 4.0.4 on 2022-06-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0003_schoolbalanceadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='pupil_code',
            field=models.PositiveIntegerField(null=True, verbose_name='Код ученика'),
        ),
    ]
