# Generated by Django 4.0.4 on 2022-06-28 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wisapp', '0004_pupil_pupil_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolbalanceadd',
            options={'verbose_name': 'АКП', 'verbose_name_plural': 'FSE'},
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('lastName', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Продавцы',
                'verbose_name_plural': 'Продавцы',
            },
        ),
    ]
