# Generated by Django 4.0.4 on 2022-06-28 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0005_alter_schoolbalanceadd_options_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperUTransPH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ManyToManyField(to='wisapp.parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.schoolbalanceuser')),
            ],
            options={
                'verbose_name': 'ПОБ история родителм',
                'verbose_name_plural': 'ПОБ история родители',
            },
        ),
        migrations.CreateModel(
            name='SuperUTransP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.PositiveIntegerField()),
                ('parent', models.ManyToManyField(to='wisapp.parent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.schoolbalanceuser')),
            ],
        ),
    ]
