# Generated by Django 4.0.4 on 2022-06-28 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0006_superutransph_superutransp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolbalanceadd',
            options={'verbose_name': 'Пополнение школьного баланса', 'verbose_name_plural': 'Пополнение школьного баланса'},
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(max_length=100)),
                ('point', models.PositiveIntegerField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('pupil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.seller')),
            ],
            options={
                'verbose_name': 'История продаж',
                'verbose_name_plural': 'История продаж',
            },
        ),
    ]
