# Generated by Django 4.0.4 on 2022-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0009_finehistory_fine_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finehistory',
            name='fine_descr',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание штрафа'),
        ),
    ]
