# Generated by Django 4.0.4 on 2022-06-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0010_alter_finehistory_fine_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='fineparent',
            name='fine_descr',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание штрафа'),
        ),
        migrations.AddField(
            model_name='fineparenthistory',
            name='fine_descr',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание штрафа'),
        ),
    ]
