# Generated by Django 4.0.4 on 2022-06-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0011_fineparent_fine_descr_fineparenthistory_fine_descr'),
    ]

    operations = [
        migrations.AddField(
            model_name='finedorzhistory',
            name='fine_descr',
            field=models.CharField(max_length=250, null=True, verbose_name='Описание штрафа'),
        ),
    ]
