# Generated by Django 4.0.4 on 2022-07-02 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0012_finedorzhistory_fine_descr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dorztransferhistory',
            name='dorz_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.dorz', verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='dorztransferhistory',
            name='pupil',
            field=models.ManyToManyField(to='wisapp.pupil', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='finedorzhistory',
            name='dorz_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.dorz', verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='finedorzhistory',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='finehistory',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.teacher', verbose_name='Имя учителя'),
        ),
        migrations.AlterField(
            model_name='finehistory',
            name='transfer_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wisapp.grade', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='fineparenthistory',
            name='parent_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.parent', verbose_name='Родители'),
        ),
        migrations.AlterField(
            model_name='parenttransferhistory',
            name='parent_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.parent', verbose_name='Родитель'),
        ),
        migrations.AlterField(
            model_name='pointtransparents',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='pointtransparents',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.parent', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='schoolbalanceadd',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='schoolbalanceuser',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='good_name',
            field=models.CharField(max_length=100, verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='pupil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.pupil', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.seller', verbose_name='Продавец'),
        ),
        migrations.AlterField(
            model_name='superutransdh',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='superutransdh',
            name='dorz',
            field=models.ManyToManyField(to='wisapp.dorz', verbose_name='Директор'),
        ),
        migrations.AlterField(
            model_name='superutransph',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='superutransph',
            name='parent',
            field=models.ManyToManyField(to='wisapp.parent', verbose_name='Родители'),
        ),
        migrations.AlterField(
            model_name='superutransth',
            name='teacher',
            field=models.ManyToManyField(to='wisapp.teacher', verbose_name='Учитель'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='teacher_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wisapp.teacher', verbose_name='Уччитель'),
        ),
        migrations.AlterField(
            model_name='transferhistory',
            name='transfer_grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='wisapp.grade', verbose_name='Класс'),
        ),
    ]
