# Generated by Django 4.0.4 on 2022-07-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0013_alter_dorztransferhistory_dorz_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fine',
            name='pupil',
        ),
        migrations.AddField(
            model_name='fine',
            name='pupil',
            field=models.ManyToManyField(to='wisapp.pupil'),
        ),
        migrations.RemoveField(
            model_name='finehistory',
            name='pupil',
        ),
        migrations.AddField(
            model_name='finehistory',
            name='pupil',
            field=models.ManyToManyField(to='wisapp.pupil', verbose_name='Выберете ученика'),
        ),
    ]
