# Generated by Django 4.0.4 on 2022-07-08 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0014_remove_fine_pupil_fine_pupil_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fineparent',
            name='pupil',
        ),
        migrations.AddField(
            model_name='fineparent',
            name='pupil',
            field=models.ManyToManyField(to='wisapp.pupil', verbose_name='Выберете ученика'),
        ),
        migrations.RemoveField(
            model_name='fineparenthistory',
            name='pupil',
        ),
        migrations.AddField(
            model_name='fineparenthistory',
            name='pupil',
            field=models.ManyToManyField(to='wisapp.pupil', verbose_name='Выберете ученика'),
        ),
    ]
