# Generated by Django 4.0.4 on 2022-07-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wisapp', '0015_remove_fineparent_pupil_fineparent_pupil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='finedorz',
            name='fine_descr',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.RemoveField(
            model_name='finedorz',
            name='pupil',
        ),
        migrations.AddField(
            model_name='finedorz',
            name='pupil',
            field=models.ManyToManyField(to='wisapp.pupil'),
        ),
        migrations.RemoveField(
            model_name='finedorzhistory',
            name='pupil',
        ),
        migrations.AddField(
            model_name='finedorzhistory',
            name='pupil',
            field=models.ManyToManyField(to='wisapp.pupil', verbose_name='Ученик'),
        ),
    ]
